In [4]:
# numpy >> numerical python
# developed in 2005 by Travis Oliphant
# before 2005, there were special mathematical tools (similar to Tora, Linga)

In [2]:
import numpy as np  #as is alias

In [3]:
np.__version__

'2.2.2'

In [5]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [6]:
lis = [1,2,3,4,"numpy_array", 4+2j, True, 1.2]
type(lis)

list

In [7]:
# Numpy stored the data in a numpy array
# An array is a container/data structure that is used to store data of same daya type(homogenous)

In [8]:
#why numpy? already we have list
# c is one of the fastest programming language
# numpy is built using c >> Therefore, it is fast
# due to array >> since, it stores only homogenous data, numpy array is faster
# since it stores homogenous data >> continuous memory location
# mathematical computation is fast

In [10]:
l = [1, 2, 3, 4, 5]

In [12]:
nump_arr = np.array(l)

In [13]:
type(nump_arr)

numpy.ndarray

In [14]:
# ndarray >> n-diamensional array

In [18]:
l = [1,2,3,4,"logitech"]
arr = np.array(l)

In [19]:
# array stores homogenous data.
# it converts the datatype of other datapoints to adjust.

In [21]:
type(arr)

numpy.ndarray

In [23]:
arr.ndim # to get the diamension of array

1

In [25]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])

In [26]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
arr1.ndim

2

In [29]:
mat = np.matrix([1,2,3,4]) #matrix is a specialised array of 2 diamensions

In [30]:
type(mat)

numpy.matrix

In [31]:
mat

matrix([[1, 2, 3, 4]])

In [32]:
# to understand the dimension, see the no. of opening/closing square bracket

In [34]:
mat2 = np.matrix([[[1,2],[2,3],[3,4]]])

ValueError: matrix must be 2-dimensional

In [38]:
arr3 = np.array([[[1,2],[2,3],[3,4]]])

In [39]:
arr3

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [40]:
arr3.ndim

3

In [41]:
# more ways to array
l = [1,2,3]
np.asarray(l) #initial function asarray to convert to an array, np.array cam after this method

array([1, 2, 3])

In [42]:
np.asanyarray(l)

array([1, 2, 3])

In [43]:
mat

matrix([[1, 2, 3, 4]])

In [45]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [46]:
t = ([1,2,3],[4,5,6])
type(t)

tuple

In [49]:
tup_np_arr = np.array(t)

In [50]:
tup_np_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr

array(['1', '2', '3', '4', 'logitech'], dtype='<U21')

In [52]:
arr[0]

'1'

In [53]:
#array is mutable
arr[0] = 192

In [54]:
arr

array(['192', '2', '3', '4', 'logitech'], dtype='<U21')

In [55]:
a = arr # a and arr will point to same memory location, so if there is change in a or arr, it will reflect on both

In [56]:
a

array(['192', '2', '3', '4', 'logitech'], dtype='<U21')

In [57]:
arr

array(['192', '2', '3', '4', 'logitech'], dtype='<U21')

In [58]:
# shallow copy >> change in one array will lead to change in another array
a[2] = 342

In [59]:
a

array(['192', '2', '342', '4', 'logitech'], dtype='<U21')

In [60]:
arr

array(['192', '2', '342', '4', 'logitech'], dtype='<U21')

In [61]:
b = arr.copy() # deep copy >> both are independent from each other

In [62]:
b

array(['192', '2', '342', '4', 'logitech'], dtype='<U21')

In [63]:
arr

array(['192', '2', '342', '4', 'logitech'], dtype='<U21')

In [64]:
b[2] = 3

In [65]:
b

array(['192', '2', '3', '4', 'logitech'], dtype='<U21')

In [66]:
arr

array(['192', '2', '342', '4', 'logitech'], dtype='<U21')

In [ ]:
# to create an array
# >> np.array
# >> np.asarray
# >> np.asanyarray

In [67]:
# multiple approaches to generate any array

In [69]:
arr1 = np.fromfunction(lambda i, j: i==j, (3,3)) # construct an array by executing a function over each coordinate

In [70]:
arr1.ndim

2

In [71]:
arr1.shape # shape of array

(3, 3)

In [72]:
arr1.size # no. of elements in array

9

In [74]:
arr2 = np.fromfunction(lambda i,j : i*j, (3,3))

In [75]:
arr2.ndim

2

In [76]:
arr2.shape

(3, 3)

In [77]:
arr2.size

9

In [78]:
for i in range(5):
  print(i)

0
1
2
3
4


In [79]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [80]:
(i for i in range(5))

<generator object <genexpr> at 0x79832d706cf0>

In [81]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [82]:
iterator = (i for i in range(5))

In [83]:
iterator

<generator object <genexpr> at 0x79832d411220>

In [84]:
np.fromiter(iterator, int) # crate a new 1D array from an iterable object

array([0, 1, 2, 3, 4])

In [85]:
np.fromstring("22 33 24", sep = " ")

array([22., 33., 24.])

In [87]:
np.fromstring("22 33 24", sep = " ", dtype=int) #by default, it is float

array([22, 33, 24])

In [88]:
# for string character, you have to use split
string = "Ajay, Bijay, Sanjay"
string.split(",")

['Ajay', ' Bijay', ' Sanjay']

In [89]:
np.array(string.split(","))

array(['Ajay', ' Bijay', ' Sanjay'], dtype='<U7')

In [90]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [92]:
# other method of numpy >> to generate a sequeunce of number
np.arange(1,10) # arange returns evenly spaced values within a given interval)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [94]:
np.linspace(1,5,10) #give me 10 numbers between 1 and 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])