In [1]:
import numpy as np

In [3]:
a = np.zeros(5)

In [4]:
a.ndim

1

In [5]:
a

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
b = np.zeros((3,4))

In [8]:
b.ndim

2

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.twos(5) #does not exist in numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [16]:
np.array([[2, 3, 4], [5, 6, 7]])

array([[2, 3, 4],
       [5, 6, 7]])

In [17]:
arr = np.zeros((3,4))

In [18]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
arr.ndim

2

In [20]:
# 3D array
np.zeros(4)

array([0., 0., 0., 0.])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
ar2 = np.zeros((3, 3, 4))

In [27]:
ar2

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
ar2.ndim

3

In [29]:
np.zeros((1,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [32]:
four_d = np.zeros((1,1,3,3))

In [33]:
four_d.ndim

4

In [34]:
arr = np.zeros((3,4))

In [35]:
arr.ndim

2

In [36]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [37]:
a = arr + 5

In [38]:
a * 2

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [39]:
a - 1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [43]:
unit_matrix = np.eye(3, dtype=int) #Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [44]:
unit_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [46]:
np.empty((2,3)) # Return a new array of given shape and type, without initializing entries. 
# It means entries in the array can be any random values

array([[1.34165069e-313, 0.00000000e+000, 6.60924056e-310],
       [0.00000000e+000, 5.49540186e-310, 6.60924031e-310]])

In [49]:
# optional >> random module
import random
random.choice((1,2,3,4,5))

4

In [50]:
random.choice("ajay")

'a'

In [51]:
random.randrange(1,37)

6

In [52]:
random.random() # a random number is generated between 0 and 1(excluded)

0.4955289731244672

In [53]:
lis = [1,2,32,35,3,1]
lis

[1, 2, 32, 35, 3, 1]

In [54]:
random.shuffle(lis)

In [55]:
lis

[1, 35, 3, 2, 1, 32]

In [56]:
random.uniform(7, 14)

11.23764484235721

In [57]:
# random numbers related concept in numpy

np.array([])

array([], dtype=float64)

In [59]:
np.random.random_sample((5, )) # 1D array of 5 random numbers

array([0.06833613, 0.79481897, 0.09136219, 0.46181555, 0.26555922])

In [60]:
np.random.rand(1)

array([0.57459496])

In [61]:
np.random.rand(2,3)

array([[0.0283367 , 0.11160299, 0.60060345],
       [0.50278319, 0.71055036, 0.51602699]])

In [62]:
np.random.randn(2,4) #Return a sample (or samples) from the "standard normal" distribution.

array([[-1.47430628,  0.28078784,  0.62147191, -0.65114607],
       [ 0.80519966,  2.36667561, -0.14390045,  1.5496025 ]])

In [65]:
arr = np.random.randint(1,5,size=(3,4)) # start from 1 and end at 4(5-1) and give array of size

In [66]:
arr.shape

(3, 4)

In [67]:
arr.ndim

2

In [71]:
# reshaping of array
ar1 = arr.reshape(2, 6) # returns an array contaning the same data with a new shape

In [72]:
ar1.size

12

In [73]:
ar1.ndim

2

In [74]:
ar1.shape

(2, 6)

In [75]:
# array size will never change, always reshape parameter should be multiplication of original array size

In [76]:
ar1.reshape(4,3)

array([[3, 1, 2],
       [1, 4, 1],
       [4, 4, 2],
       [1, 3, 4]])

In [77]:
ar1.reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [78]:
ar1.reshape(6,2)

array([[3, 1],
       [2, 1],
       [4, 1],
       [4, 4],
       [2, 1],
       [3, 4]])

In [79]:
# case when you don't know what should be the row or column count while reshaping
# use any negative value for rows or columns
ar1.reshape(4,-1)

array([[3, 1, 2],
       [1, 4, 1],
       [4, 4, 2],
       [1, 3, 4]])

In [80]:
arr.reshape(2,-1983)

array([[3, 1, 2, 1, 4, 1],
       [4, 4, 2, 1, 3, 4]])

In [81]:
arr.reshape(-382, 12)

array([[3, 1, 2, 1, 4, 1, 4, 4, 2, 1, 3, 4]])

In [82]:
ar1

array([[3, 1, 2, 1, 4, 1],
       [4, 4, 2, 1, 3, 4]])

In [84]:
ar1.reshape(12,1).base # to see the original array

array([[3, 1, 2, 1],
       [4, 1, 4, 4],
       [2, 1, 3, 4]])

In [87]:
arr.reshape(2, 2, 3) # repetition of two times.

array([[[3, 1, 2],
        [1, 4, 1]],

       [[4, 4, 2],
        [1, 3, 4]]])

In [93]:
arr.reshape(1,2,2,3)

array([[[[3, 1, 2],
         [1, 4, 1]],

        [[4, 4, 2],
         [1, 3, 4]]]])

In [94]:
arr.ndim

2

In [97]:
arr.reshape(4,3,1) # 3 rows, 1 column repreated 4 times in the third dimension

array([[[3],
        [1],
        [2]],

       [[1],
        [4],
        [1]],

       [[4],
        [4],
        [2]],

       [[1],
        [3],
        [4]]])

In [99]:
# conditions on array
arr1 = np.random.randint(1,10,(5,6))

In [100]:
arr1

array([[1, 7, 6, 5, 9, 6],
       [2, 6, 6, 4, 1, 9],
       [7, 6, 2, 9, 1, 4],
       [1, 2, 3, 3, 7, 8],
       [8, 4, 5, 6, 7, 9]])

In [101]:
arr1.shape

(5, 6)

In [102]:
arr1.size

30

In [103]:
arr1.ndim

2

In [104]:
arr1 > 3

array([[False,  True,  True,  True,  True,  True],
       [False,  True,  True,  True, False,  True],
       [ True,  True, False,  True, False,  True],
       [False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [105]:
arr1[arr1 > 3] # select all the elements of arr1 where the condition is true

array([7, 6, 5, 9, 6, 6, 6, 4, 9, 7, 6, 9, 4, 7, 8, 8, 4, 5, 6, 7, 9])

In [106]:
arr1

array([[1, 7, 6, 5, 9, 6],
       [2, 6, 6, 4, 1, 9],
       [7, 6, 2, 9, 1, 4],
       [1, 2, 3, 3, 7, 8],
       [8, 4, 5, 6, 7, 9]])

In [107]:
# to access elements in an array

In [108]:
arr1[0]

array([1, 7, 6, 5, 9, 6])

In [109]:
arr1[1]

array([2, 6, 6, 4, 1, 9])

In [112]:
arr1[1][4]

np.int64(1)

In [113]:
arr1

array([[1, 7, 6, 5, 9, 6],
       [2, 6, 6, 4, 1, 9],
       [7, 6, 2, 9, 1, 4],
       [1, 2, 3, 3, 7, 8],
       [8, 4, 5, 6, 7, 9]])

In [114]:
arr1[3][1]

np.int64(2)

In [115]:
arr1

array([[1, 7, 6, 5, 9, 6],
       [2, 6, 6, 4, 1, 9],
       [7, 6, 2, 9, 1, 4],
       [1, 2, 3, 3, 7, 8],
       [8, 4, 5, 6, 7, 9]])

In [116]:
# from 0th row to 2nd row
arr1[0:3]

array([[1, 7, 6, 5, 9, 6],
       [2, 6, 6, 4, 1, 9],
       [7, 6, 2, 9, 1, 4]])

In [117]:
# from 0th row to 2nd row and 0th and 2nd column
arr1[0:3,[0,2]]

array([[1, 6],
       [2, 6],
       [7, 2]])

In [118]:
# slicing on both rows and columns together
arr1

array([[1, 7, 6, 5, 9, 6],
       [2, 6, 6, 4, 1, 9],
       [7, 6, 2, 9, 1, 4],
       [1, 2, 3, 3, 7, 8],
       [8, 4, 5, 6, 7, 9]])

In [119]:
arr1[0:3, 1:3]

array([[7, 6],
       [6, 6],
       [6, 2]])

In [120]:
arr1[0:3,[0,1]]

array([[1, 7],
       [2, 6],
       [7, 6]])

In [122]:
arr1[0,[1,3]]

array([7, 5])

In [123]:
arr1[2:4, [0,3]]

array([[7, 9],
       [1, 3]])

In [124]:
arr1

array([[1, 7, 6, 5, 9, 6],
       [2, 6, 6, 4, 1, 9],
       [7, 6, 2, 9, 1, 4],
       [1, 2, 3, 3, 7, 8],
       [8, 4, 5, 6, 7, 9]])

In [125]:
arr1[2:5, 0:2]

array([[7, 6],
       [1, 2],
       [8, 4]])

In [126]:
# mathematical operations on two arrays
arr1 = np.random.randint(1,4,(3,3))
arr2 = np.random.randint(1,5,(3,3))

In [127]:
arr1

array([[2, 2, 2],
       [2, 3, 3],
       [2, 3, 3]])

In [128]:
arr2

array([[3, 4, 1],
       [1, 3, 3],
       [4, 2, 4]])

In [129]:
arr1 + arr2 # indexwise element addition

array([[5, 6, 3],
       [3, 6, 6],
       [6, 5, 7]])

In [130]:
arr1 - arr2 # indexwise subtraction

array([[-1, -2,  1],
       [ 1,  0,  0],
       [-2,  1, -1]])

In [131]:
arr1 * arr2 # indexwise multiplication

array([[ 6,  8,  2],
       [ 2,  9,  9],
       [ 8,  6, 12]])

In [132]:
arr1, arr2

(array([[2, 2, 2],
        [2, 3, 3],
        [2, 3, 3]]),
 array([[3, 4, 1],
        [1, 3, 3],
        [4, 2, 4]]))

In [133]:
arr1 / arr2 # indexwise division

array([[0.66666667, 0.5       , 2.        ],
       [2.        , 1.        , 1.        ],
       [0.5       , 1.5       , 0.75      ]])

In [134]:
arr1/0

/tmp/ipykernel_2427/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [135]:
# matrix muliplication >> matrix is a specialised 2D array
# matrix muliplication differs from index-wise multiplication

In [136]:
arr1 @ arr2

array([[16, 18, 16],
       [21, 23, 23],
       [21, 23, 23]])

In [137]:
np.dot(arr1, arr2)

array([[16, 18, 16],
       [21, 23, 23],
       [21, 23, 23]])

In [138]:
# broadcasting
arr = np.zeros((3,4))

In [139]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [140]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [141]:
a = np.array([1,2,3,4])

In [142]:
a

array([1, 2, 3, 4])

In [143]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [144]:
a+arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [145]:
a

array([1, 2, 3, 4])

In [147]:
# Transpose >> converting the rows to columns and columns to rows
a.T

array([1, 2, 3, 4])

In [148]:
a.T

array([1, 2, 3, 4])

In [149]:
arr1

array([[2, 2, 2],
       [2, 3, 3],
       [2, 3, 3]])

In [150]:
arr1.T

array([[2, 2, 2],
       [2, 3, 3],
       [2, 3, 3]])

In [151]:
a2 = a+arr

In [152]:
a2

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [153]:
a2.T

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])