In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [3]:
arr1

array([[2, 2, 2],
       [2, 1, 1],
       [2, 1, 1]])

In [4]:
arr2

array([[2, 2, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [5]:
arr1.flatten() # return a copy of the array collapsed into 1D

array([2, 2, 2, 2, 1, 1, 2, 1, 1])

In [6]:
# expand dimension
arr = np.array([1,2,3,4])

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
arr.ndim

1

In [11]:
np.expand_dims(arr, axis=0) # Insert a new axis that will appear at the axis position in the expanded array shape.
# increase the dimension by 1 in the provided axis, 0 means rows(x axis), 1 means columns(y axis)

array([[1, 2, 3, 4]])

In [12]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [13]:
np.expand_dims(arr, axis=1).ndim

2

In [14]:
arr = np.zeros((3,4))

In [15]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.expand_dims(arr, axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
np.expand_dims(arr, axis=0).ndim

3

In [18]:
np.expand_dims(arr, axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [20]:
np.expand_dims(arr, axis=1).ndim

3

In [21]:
a = np.array([[1], [2], [3]])

In [22]:
a

array([[1],
       [2],
       [3]])

In [23]:
a.ndim

2

In [26]:
# squeezing the dimension
np.squeeze(a) # remove axes of length 1 from 'a'


array([1, 2, 3])

In [27]:
a

array([[1],
       [2],
       [3]])

In [28]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [29]:
arr1

array([[2, 2, 2],
       [2, 1, 1],
       [2, 1, 1]])

In [30]:
np.repeat(arr1, 2)

array([2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1])

In [31]:
np.repeat(arr1,2,axis=0)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 1]])

In [32]:
arr2

array([[2, 2, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [33]:
np.repeat(arr2, 3, axis=0)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [34]:
np.repeat(arr2, 3, axis=1)

array([[2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [35]:
a

array([[1],
       [2],
       [3]])

In [36]:
np.roll(a, -1)

array([[2],
       [3],
       [1]])

In [ ]:
np.roll(a, -2)