In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [3]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [2, 2, 2]])

In [4]:
arr2

array([[2, 2, 2],
       [1, 2, 2],
       [2, 2, 1]])

In [5]:
arr1.flatten() # return a copy of the array collapsed into 1D

array([1, 1, 2, 2, 2, 1, 2, 2, 2])

In [6]:
# expand dimension
arr = np.array([1,2,3,4])

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
arr.ndim

1

In [9]:
np.expand_dims(arr, axis=0) # Insert a new axis that will appear at the axis position in the expanded array shape.
# increase the dimension by 1 in the provided axis, 0 means rows(x axis), 1 means columns(y axis)

array([[1, 2, 3, 4]])

In [10]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [11]:
np.expand_dims(arr, axis=1).ndim

2

In [12]:
arr = np.zeros((3,4))

In [13]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.expand_dims(arr, axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
np.expand_dims(arr, axis=0).ndim

3

In [16]:
np.expand_dims(arr, axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [17]:
np.expand_dims(arr, axis=1).ndim

3

In [18]:
a = np.array([[1], [2], [3]])

In [19]:
a

array([[1],
       [2],
       [3]])

In [20]:
a.ndim

2

In [21]:
# squeezing the dimension
np.squeeze(a) # remove axes of length 1 from 'a'


array([1, 2, 3])

In [22]:
a

array([[1],
       [2],
       [3]])

In [23]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [24]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [2, 2, 2]])

In [25]:
np.repeat(arr1, 2)

array([1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2])

In [26]:
np.repeat(arr1,2,axis=0)

array([[1, 1, 2],
       [1, 1, 2],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [27]:
arr2

array([[2, 2, 2],
       [1, 2, 2],
       [2, 2, 1]])

In [28]:
np.repeat(arr2, 3, axis=0)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [1, 2, 2],
       [1, 2, 2],
       [1, 2, 2],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [29]:
np.repeat(arr2, 3, axis=1)

array([[2, 2, 2, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 1, 1, 1]])

In [30]:
a

array([[1],
       [2],
       [3]])

In [31]:
np.roll(a, -1)

array([[2],
       [3],
       [1]])

In [32]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [34]:
c = np.array([[1,2],[3,4],[5,6],[7,8]])

In [35]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [36]:
np.roll(c,-1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [37]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [38]:
np.roll(c,2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [39]:
np.roll(c,2,axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [40]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [2, 2, 2]])

In [41]:
arr2

array([[2, 2, 2],
       [1, 2, 2],
       [2, 2, 1]])

In [42]:
arr1+arr2

array([[3, 3, 4],
       [3, 4, 3],
       [4, 4, 3]])

In [43]:
arr1-arr2

array([[-1, -1,  0],
       [ 1,  0, -1],
       [ 0,  0,  1]])

In [44]:
arr1*arr2

array([[2, 2, 4],
       [2, 4, 2],
       [4, 4, 2]])

In [45]:
arr1>arr2

array([[False, False, False],
       [ True, False, False],
       [False, False,  True]])

In [47]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [2, 2, 2]])

In [48]:
~arr1

array([[-2, -2, -3],
       [-3, -3, -2],
       [-3, -3, -3]])

In [49]:
# operations on numpy string array

d = np.array(["pw", "skills"])

In [50]:
d

array(['pw', 'skills'], dtype='<U6')

In [51]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [52]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [53]:
# mathematical function

In [54]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [2, 2, 2]])

In [55]:
np.sin(arr1)

array([[0.84147098, 0.84147098, 0.90929743],
       [0.90929743, 0.90929743, 0.84147098],
       [0.90929743, 0.90929743, 0.90929743]])

In [56]:
np.cos(arr1)

array([[ 0.54030231,  0.54030231, -0.41614684],
       [-0.41614684, -0.41614684,  0.54030231],
       [-0.41614684, -0.41614684, -0.41614684]])

In [57]:
np.tan(arr1)

array([[ 1.55740772,  1.55740772, -2.18503986],
       [-2.18503986, -2.18503986,  1.55740772],
       [-2.18503986, -2.18503986, -2.18503986]])

In [58]:
np.log10(arr1)

array([[0.     , 0.     , 0.30103],
       [0.30103, 0.30103, 0.     ],
       [0.30103, 0.30103, 0.30103]])

In [59]:
np.exp(arr1)

array([[2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 7.3890561 , 7.3890561 ]])

In [60]:
np.power(arr1,3)

array([[1, 1, 8],
       [8, 8, 1],
       [8, 8, 8]])

In [61]:
np.max(arr1)

np.int64(2)

In [62]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [2, 2, 2]])

In [63]:
np.mean(arr1)

np.float64(1.6666666666666667)

In [64]:
np.min(arr1)

np.int64(1)

In [65]:
np.std(arr1)

np.float64(0.4714045207910317)

In [66]:
np.var(arr1)

np.float64(0.2222222222222222)

In [67]:
np.subtract(arr1,arr2)

array([[-1, -1,  0],
       [ 1,  0, -1],
       [ 0,  0,  1]])

In [69]:
np.multiply(arr1,arr2)

array([[2, 2, 4],
       [2, 4, 2],
       [4, 4, 2]])

In [70]:
np.mod(arr1,arr2) # return element-wise remainder

array([[1, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [71]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.41421356]])

In [73]:
# sorting and searching in numpy array
e = np.array([5,6,2,8])

In [74]:
e

array([5, 6, 2, 8])

In [75]:
np.sort(e)

array([2, 5, 6, 8])

In [76]:
f = np.array([5,3,6,22,98,111])
f

array([  5,   3,   6,  22,  98, 111])

In [77]:
np.sort(f)

array([  3,   5,   6,  22,  98, 111])

In [78]:
np.searchsorted(f, 170) #find indices where elements should be inserted to maintain order

np.int64(6)

In [79]:
f = np.array([5,3,6,22,0,0,0,98,0,111])
f

array([  5,   3,   6,  22,   0,   0,   0,  98,   0, 111])

In [80]:
np.count_nonzero(f)

6

In [81]:
f[f>0]

array([  5,   3,   6,  22,  98, 111])

In [82]:
np.where(f>0)

(array([0, 1, 2, 3, 7, 9]),)

In [83]:
np.extract(f>0, f)

array([  5,   3,   6,  22,  98, 111])

In [84]:
f.byteswap() # swap the bytes of the array elements

array([ 360287970189639680,  216172782113783808,  432345564227567616,
       1585267068834414592,                   0,                   0,
                         0, 7061644215716937728,                   0,
       7998392938210000896])

In [85]:
import numpy.matlib as nm
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [95]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [88]:
# numpy linear algebra

In [89]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [2, 2, 2]])

In [90]:
arr2

array([[2, 2, 2],
       [1, 2, 2],
       [2, 2, 1]])

In [91]:
arr1*arr2

array([[2, 2, 4],
       [2, 4, 2],
       [4, 4, 2]])

In [96]:
nm.linalg.det(arr1)

np.float64(0.0)

In [97]:
nm.linalg.det(arr2)

np.float64(-2.0)

In [98]:
# inverse of matrix
nm.linalg.inv(arr2)

array([[ 1. , -1. ,  0. ],
       [-1.5,  1. ,  1. ],
       [ 1. , -0. , -1. ]])

In [99]:
# solving linear equations
a = np.array([[7, 5.3, -3],[3, -5, 2],[5, 3, -7]])
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [100]:
b = np.array([18,8,2])

In [101]:
np.linalg.solve(a,b)

array([2.7817565 , 0.90463626, 2.0889559 ])